[project]
name = "reto-winter-2025-google-grupo1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.28.0",
    "pydantic>=2.11.7",
    "google-cloud-storage>=2.10.0",
    "google-cloud-bigquery>=3.11.0",
    "google-cloud-aiplatform>=1.38.0",
    "unstructured>=0.7.0",
    "python-docx>=0.8.11",
    "openpyxl>=3.1.2",

]

[tool.ruff]
line-length = 100

[tool.uv]
package = true
