[project]
name = "reto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.28.0",
    "gradio>=5.39.0",
    "pydantic>=2.11.7",
    "pydantic-ai>=0.4.11",
    "google-cloud-storage>=2.10.0",
    "google-cloud-bigquery>=3.11.0",
    "google-cloud-aiplatform>=1.38.0",
    "google-auth>=2.15.0",
    "google-generativeai>=0.8.0",
    "unstructured>=0.7.0",
    "python-docx>=0.8.11",
    "openpyxl>=3.1.2",
    "PyPDF2>=3.0.0",
    "numpy>=1.24.0",
    "python-dotenv>=1.0.0",
]

[tool.ruff]
line-length = 100

[tool.uv]
package = true
