[project]
name = "reto-winter-2025-google-grupo1"
version = "0.1.0"
description = "Chatbot for Centro Ithaka"
authors = [
	{ name = "Santiago Panozzo", email = "santiagopanozzoa@outlook.com" },
	{ name = "Cristian Rodriguez", email = "ezponjares@gmail.com" },
	{ name = "Francisco Nasso", email = "Francisconasso@gmail.com" },
	{ name = "Milagros Kucharski", email = "milakuchper@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.28.0",
    "gradio>=5.39.0",
    "pydantic>=2.11.7",
]

[tool.ruff]
line-length = 100

[tool.uv]
package = true
